### ISSUE TITLE
此插件是单线程的吗？

### ISSUE THREAD

**Issue by crixusshen** [bubkoo/grunt-restful-mock#8]
如果同时访问，需要等待前一个接口输出结果后才请求第二个接口，请问是否支持多线程

**Comment by bubkoo** [comment]
@crixusshen 
首先，NodeJS 是单线程的，而接口实现是异步的方式，每接受到一个请求后就开始异步取数据，这时也可以处理下一个请求，每当数据处理完成后就立即返回；然后，你所说的阻塞的情况，应该是线程的很多时间被用于生成随机数了，后面我会考虑支持用子进程去生成数据。

**Comment by crixusshen** [comment]
@bubkoo 
好的，现在基本都采用Promise+的规范，特别在某些场景下确实需要同时获取好几个接口，当接口（当然都是异步的）数据全部返回后渲染界面，在这种情况下就希望mock可以提供一个类似多线程的环境，不然在测试过程中将会产生额外的时间消耗开销。github上有一个kriskowal/asap的实现，是基于多任务多线程的，实现很简单也提供了browser的支持，建议采用这样的机制来生成数据。

**Comment by bubkoo** [comment]
@crixusshen 建议很好，我会尽快找方案实现，当然你也可以提交 [pull request](https://github.com/bubkoo/grunt-restful-mock/pulls)，欢迎贡献代码。

:+1: :+1: :+1:
